#comentario
(7*3)+12/2-7^2+sqrt(4)
log(3)+sqrt(2)*sin(pi/4)-exp(3)
3+2+log(5)+exp(3)/4+sqrt(6)
x<-0.28354
round(x,2)
x<-7
rm(x)
x<-2
y<-5
z<-(x*y)
ls()
rm(list=ls())
ls()
x<-c(1.5,2,3)
x
y<-x^2
y
which(y==4)
y<-c("A","table","book")
y
x<-c(2,3,4,1)
y<-c(1,1,3,7)
x
y
x+y
cbind(x,y)
rbind(x,y)
fich<-data.frame(x,y)
fich
seq(0,1,0.2)
seq(0,8)
seq(,8)
seq(8,1,-1)
seq(8,1)
seq(8,1,-0.2)
rep(1,5)
z<-rep(1,5)
rm(z)
c(rep(1,3),rep(2,3),rep(3,3))
z<-c(rep(1,3),rep(2,3),rep(3,3))
z[1]
z[c(1,4,5)]
library(PASWR2)
head(SWIMTIMES)
tail(SWIMTIMES)
summary(SWIMTIMES)
str(SWIMTIMES)
SWIMTIMES$seconds
o<-order(SWIMTIMES$seconds,decreasing=TRUE)
SWIMTIMES[o,]
SWIMTIMES2<-SWIMTIMES[o,]
SWIMTIMES2
table(SWIMTIMES$diet)
with(SWIMTIMES,table(diet))
high.fat<-SWIMTIMES[SWIMTIMES$diet=="highfat",]
high.fat
seconds.value<-with(SWIMTIMES,seconds[seconds<1])
seconds.value
seconds.value2<-subset(SWIMTIMES,seconds>2&seconds!=2.66)
seconds.value2
min(SWIMTIMES$seconds)
max(SWIMTIMES$seconds)
range(SWIMTIMES$seconds)
SWIMTIMES$time<-0
SWIMTIMES[SWIMTIMES$seconds>1,"time"]<-1
SWIMTIMES
SWIMTIMES2<-SWIMTIMES[,-2]
SWIMTIMES2
SWIMTIMES3<-SWIMTIMES[-(1:3),]
SWIMTIMES3
eda(SWIMTIMES$seconds)
boxplot(SWIMTIMES3$seconds,col="red")
hist(SWIMTIMES3$seconds,col="blue")
X<-table(SWIMTIMES3$diet)
barplot(X,col="green")